language: python
python: 3.6
install:
- pip install coveralls nose
- pip install .
script:
- nosetests --with-coverage --cover-package=keepass_getter
after_success:
- coveralls
deploy:
  provider: pypi
  user: M-Gregoire
  password:
    secure: wGTwK7GrvrIY2Kxwdj/1vadeAxhqORGu6ny8s/Uf3DUxa41/WwBSkPraml2BcF2drnAxUAoLmmXvrQVAM7CWLSlzqzcB+t7KmSeD4wKWRDOFtmQj8Ae5coEXQx1ZcKwRQ6bqZxPBipsaQavo6+rDwLNbcXJQcc3MTKV1SjrwkPqzm21nSofDZim7qno/or4XnlSt/WRwv2rAVGTsG1EIQ3XjFoE62mMCi7ISNJhGMSVNqCzfWxPEtzy5INdB4P2p/rOLuTwPIZPWfuyxGh2TrzroOxm74srUydotMred+/zg99gM6C3w6pMgi0Gq/yloEecQIzkR8mbR1NlNmlm1U7CeFmRZtV2S9rw6ABBvJUmHuuCc/3+vP1yApem6JmklPq2o6dDfLhKVZVeA6uHBwFACC44cEs2hAMDh1iknT7rhtinsvies+SNMarOcymMQwRFh8WU9TaL408p0is6+S3eQURHJL4b7zHLSaN79nHB1MYBP6b3YU2Phx/x2TQDHWHxSjHzFplMSzA9wMyfv2Lh5cv+UhS6TzXUZ2huscq4JBlOHKIqtoOXeYMR0jkH4ds7ofEqzk9NhRZjSp7P3JzbDCwqiEzg8jTBP1r2GfVaaY05c8wqEPtuYgGnvDHhPR2ydxkQpY6ptWBOCnatPjqiAXSKHTV/qLkkKVm9g/i4=
